### ISSUE TITLE
GitHub integration with UI

### ISSUE THREAD

**Issue by sambit985** [sambit985/LdTech-DevApp#1]
1. When user click on TestConnection button authenticate status should display.
2. when click on authorize button users github repo, email, last status should display.
![github02](https://github.com/sambit985/LdTech-DevApp/assets/77062786/e141157b-c24f-4f23-9814-8bf3f61a747c)

**Comment by mhamzanadeem** [comment]
can i contribute to it .

Can u tell me where can i get the code of this issue in your repo ?

**Comment by sambit985** [comment]
> can i contribute to it .
> 
> Can u tell me where can i get the code of this issue in your repo ?

For this api you need to develop api using nodejs/expressjs to fetch user github repository. Do you have back-end skill?

**Comment by mhamzanadeem** [comment]
> > can i contribute to it .
> > Can u tell me where can i get the code of this issue in your repo ?
> 
> For this api you need to develop api using nodejs/expressjs to fetch user github repository. Do you have back-end skill?

I dont have back-end skill :(

**Comment by sambit985** [comment]
> > > can i contribute to it .
> > > Can u tell me where can i get the code of this issue in your repo ?
> > 
> > 
> > For this api you need to develop api using nodejs/expressjs to fetch user github repository. Do you have back-end skill?
> 
> I dont have back-end skill :(

No problem focus on your skill and develop your hands-on experience. You can work on other issues which is open for Frontend.

**Comment by sambit985** [comment]
This part has completed.
Thanks to all who are tried their best.
@mhamzanadeem
