### ISSUE TITLE
Add forget password section in Signin page

### ISSUE THREAD

**Issue by sambit985** [sambit985/LdTech-DevApp#2]
1. Add forget password section in Signin page using reactjs. 
2. When click on forget password one page should open where enter email and forget password button is there.
3. After email input and click on forget password button one reset link must be send to the email for reset.

**Comment by mhamzanadeem** [comment]
can i work on this issue

**Comment by mhamzanadeem** [comment]
![Screenshot 2023-09-03 173836](https://github.com/sambit985/LdTech-DevApp/assets/114602354/bbe29e83-e3aa-4f66-ac76-01d1d19fc3ee)

Do u want here to display "forget password " on sign in page ?

**Comment by mhamzanadeem** [comment]
You have written that "When click on forget password one page should open where enter email and forget password button is there. " .   Should I make a separate  "forget password page "  and then i make a input box (to enter email address) and forget password button ?

**Comment by sambit985** [comment]
> ![Screenshot 2023-09-03 173836](https://user-images.githubusercontent.com/114602354/265264626-bbe29e83-e3aa-4f66-ac76-01d1d19fc3ee.png)
> 
> Do u want here to display "forget password " on sign in page ?

Add forgot password below the password input section and above login button

**Comment by mhamzanadeem** [comment]
> You have written that "When click on forget password one page should open where enter email and forget password button is there. " . Should I make a separate "forget password page " and then i make a input box (to enter email address) and forget password button ?

can u also explain me this thing

**Comment by sambit985** [comment]
> You have written that "When click on forget password one page should open where enter email and forget password button is there. " . Should I make a separate "forget password page " and then i make a input box (to enter email address) and forget password button ?

**Yes create one component for forgot password where one email input box and forgot password button is available by which user can change their password and for routing follow App.js file**

@mhamzanadeem great for us if you add functionality such as after click on that button email should be sent for the password change/update.

**Comment by mhamzanadeem** [comment]
I have read backend code .  You have used Express.js .  i haven't learn Express.js  . 
I have made a separate component of Forget password .
should  I do pull request ?

**Comment by sambit985** [comment]
Thanks for showing interest on our project, Yeah sure you can add pull request for code review

**Comment by mhamzanadeem** [comment]
> Thanks for showing interest on our project, Yeah sure you can add pull request for code review. Tomorrow I'm going to close this issue you can work on other issues for the future reference from my side.

Thanks. I have done pull request

**Comment by sambit985** [comment]
**Thanks Everyone who tried to contribute**
