### ISSUE TITLE
Signup Validation 

### ISSUE THREAD

**Issue by sambit985** [sambit985/LdTech-DevApp#4]
- Password length should be minimum 8 charecter maximum 255 charecter for Signup page.
- username length should not be less than 5 charecter for Signup.

**Comment by mhamzanadeem** [comment]
can i work on this bug  ?

**Comment by sambit985** [comment]
> can i work on this bug ?

Yes you can work on this bug @mhamzanadeem

**Comment by mhamzanadeem** [comment]
I have fixed the issue . 

Now the signup will look like this

![Screenshot 2023-09-08 183633](https://github.com/sambit985/LdTech-DevApp/assets/114602354/5f80087b-7a06-4aa9-a681-63178778db1d)

![Screenshot 2023-09-08 183659](https://github.com/sambit985/LdTech-DevApp/assets/114602354/4a1d0f6e-b46c-425c-bdfc-a9a85fdec452)

**Comment by sambit985** [comment]
Well @mhamzanadeem now you can pull request the code whatever you have done. We will review your code.
